version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests.dev
    command: ['dotnet', 'test', './JwtServer.Tests']
  tokenserver:
    build:
      context: .
      dockerfile: Dockerfile.tokenserver.dev
    restart: always
  queryserver:
    build:
      context: .
      dockerfile: Dockerfile.queryserver.dev
    restart: always
  nginx:
    restart: always
    build:
      context: ./Nginx
      dockerfile: Dockerfile.dev
    ports:
      - '1234:80'
