version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: Docker/Dockerfile.tests.dev
    command: ['dotnet', 'test', './JwtServer.Tests']
  tokenserver:
    build:
      context: .
      dockerfile: Docker/Dockerfile.tokenserver.dev
    restart: always
    image: jackula83/jwt-token-server
  queryserver:
    build:
      context: .
      dockerfile: Docker/Dockerfile.queryserver.dev
    restart: always
    image: jackula83/jwt-query-server
  nginx:
    restart: always
    build:
      context: ./Nginx
      dockerfile: Dockerfile.dev
    ports:
      - '1234:80'
    image: jackula83/jwt-nginx
