FROM mcr.microsoft.com/dotnet/core/sdk:3.1

WORKDIR /app

# Copy csproj and restore as distinct layers
COPY JwtServer.Tests/*.csproj ./JwtServer.Tests/
COPY JwtTokenServer/*.csproj ./JwtTokenServer/
COPY JwtQueryServer/*.csproj ./JwtQueryServer/
COPY JwtUtilities/*.csproj ./JwtUtilities/
RUN dotnet restore ./JwtServer.Tests/JwtServer.Tests.csproj

# Run tests on build
COPY . ./
RUN dotnet test ./JwtServer.Tests
