FROM mcr.microsoft.com/dotnet/core/sdk:3.1

WORKDIR /app

# Copy csproj and restore as distinct layers
COPY JwtTokenServer/*.csproj ./JwtTokenServer/
COPY JwtUtilities/*.csproj ./JwtUtilities/
RUN dotnet restore ./JwtTokenServer/JwtTokenServer.csproj

# Copy everything else and build
COPY . ./
RUN dotnet publish ./JwtTokenServer -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=0 /app/out .
ENTRYPOINT ["dotnet", "JwtTokenServer.dll"]